<a href="https://colab.research.google.com/github/choeuneheol/python-practice/blob/master/%EC%9E%90%EC%97%B0%EC%96%B4%EC%B2%98%EB%A6%ACDAY8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
# #RNN
# #Recument Neural Network

# from tensorflow.keras.layers import SimpleRNN
# model.add(SimpleRNN(hidden_units))

# model.add(SimpleRNN(hidden_units, input_shape=(timesteps, input_dim)))
# #model.add(SimpleRNN(hidden_units, input_length=M, input_dim=N))

In [26]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN

model = Sequential()
model.add(SimpleRNN(3, input_shape=(2,10)))
# model.add(SimpleRNN(3, input_length=2, input_dim=10))와 동일함.
model.summary()


Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_16 (SimpleRNN)   (None, 3)                 42        
                                                                 
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [27]:
model = Sequential()
model.add(SimpleRNN(3, batch_input_shape=(8,2,10)))
model.summary()

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_17 (SimpleRNN)   (8, 3)                    42        
                                                                 
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [28]:
model = Sequential()
model.add(SimpleRNN(3, batch_input_shape=(8,2,10),return_sequences=True))
model.summary()

Model: "sequential_12"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_18 (SimpleRNN)   (8, 2, 3)                 42        
                                                                 
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [29]:
#RNN 파이썬 구현

import numpy as np
timesteps =10
input_dim=4
hidden_units = 8
inputs = np.random.random((timesteps, input_dim))
hidden_state_t=np.zeros((hidden_units,))
print('초기 은닉 상태 :', hidden_state_t)

초기 은닉 상태 : [0. 0. 0. 0. 0. 0. 0. 0.]


In [30]:
inputs

array([[0.22134972, 0.16531696, 0.4335822 , 0.995191  ],
       [0.73846026, 0.27243618, 0.12125189, 0.69179506],
       [0.31193616, 0.39397884, 0.27488944, 0.82508895],
       [0.35757967, 0.57892659, 0.92086245, 0.94119677],
       [0.98392506, 0.17164423, 0.15200987, 0.12941719],
       [0.41682009, 0.7070914 , 0.04366301, 0.30986553],
       [0.05658912, 0.632865  , 0.82338625, 0.8241708 ],
       [0.1072109 , 0.06789916, 0.75401863, 0.88750227],
       [0.96785161, 0.83982441, 0.599203  , 0.78043346],
       [0.05581218, 0.7329914 , 0.22707397, 0.7429134 ]])

In [31]:
Wx = np.random.random((hidden_units, input_dim))
Wh = np.random.random((hidden_units, hidden_units))
b = np.random.random((hidden_units,))
print('가중치 Wx의 크기(shape):',np.shape(Wx))
print('가중치 Wx의 크기(shape):',np.shape(Wh))
print('편향의 크기(shape) :',np.shape(b))

가중치 Wx의 크기(shape): (8, 4)
가중치 Wx의 크기(shape): (8, 8)
편향의 크기(shape) : (8,)


In [32]:
total_hidden_states=[]
for input_t in inputs:
  output_t = np.tanh(np.dot(Wx, input_t)+ np.dot(Wh,hidden_state_t)+b)
  total_hidden_states.append(list(output_t))
  hidden_state_t = output_t

total_hidden_states = np.stack(total_hidden_states, axis=0)
print('모든 시점의 은닉 상태:')
print(total_hidden_states)

모든 시점의 은닉 상태:
[[0.91172775 0.76270401 0.94380853 0.90285785 0.89254624 0.91863956
  0.89721348 0.51660252]
 [0.99996232 0.99988046 0.99990393 0.99999353 0.99977148 0.99991764
  0.99994553 0.99969187]
 [0.99998223 0.99995417 0.99998204 0.99999818 0.99995014 0.99997615
  0.99997934 0.9999444 ]
 [0.99999309 0.99997276 0.99999666 0.99999921 0.99998675 0.99998931
  0.99999035 0.99996769]
 [0.99998914 0.99997719 0.99995145 0.99999672 0.99992956 0.99996289
  0.99998131 0.99993603]
 [0.99997407 0.99996546 0.99997297 0.99999745 0.99994974 0.99998037
  0.99998435 0.99995059]
 [0.99998492 0.99995818 0.99999523 0.99999851 0.9999787  0.99998552
  0.99998412 0.99996504]
 [0.99998282 0.99993662 0.99998747 0.99999682 0.99994026 0.99995862
  0.99995925 0.99994344]
 [0.99999696 0.9999891  0.9999964  0.99999971 0.99999315 0.99999512
  0.99999707 0.9999718 ]
 [0.99997068 0.99994881 0.99998615 0.99999815 0.99995931 0.99998321
  0.99998209 0.99995404]]


In [33]:
from tensorflow.keras.layers import Bidirectional
timesteps=10
input_dim = 5
model= Sequential()
model.add(Bidirectional(SimpleRNN(hidden_units, return_sequences=True), input_shape=(timesteps, input_dim)))

In [34]:
model = Sequential()
model.add(Bidirectional(SimpleRNN(hidden_units, return_sequences=True), input_shape=(timesteps, input_dim)))
model.add(Bidirectional(SimpleRNN(hidden_units, return_sequences=True)))
model.add(Bidirectional(SimpleRNN(hidden_units, return_sequences=True)))
model.add(Bidirectional(SimpleRNN(hidden_units, return_sequences=True)))

In [35]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN, LSTM, Bidirectional

train_x = [[0.1, 4.2, 1.5, 1.1, 1.8],[1.0, 3.1, 2.5, 0.7, 1.1],[0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]
print(np.shape(train_x))

train_x = [[[0.1, 4.2, 1.5, 1.1, 2.8],[1.0,3.1,2.5,0.7,1.1],[0.3,2.1,1.5,2.1,0.1],[2.2,1.4,0.5,0.9,1.1]]]
train_x = np.array(train_x, dtype=np.float32)
print(train_x.shape)

(4, 5)
(1, 4, 5)


In [36]:
rnn = SimpleRNN(3)
hidden_state = rnn(train_x)
print('hidden state : {}, shape: {}'.format(hidden_state,hidden_state.shape))

hidden state : [[ 0.9650942   0.95050406 -0.37150925]], shape: (1, 3)


In [41]:
rnn = SimpleRNN(3, return_sequences=True)
hidden_state = rnn(train_x)
print('hidden states : {}, shape:{}'.format(hidden_state, hidden_state.shape))

hidden states : [[[ 0.9964961   0.3588689  -0.9942177 ]
  [ 0.9874585   0.56711155  0.7018847 ]
  [-0.00404564 -0.67711824  0.5500403 ]
  [ 0.9138429   0.93025666 -0.5733064 ]]], shape:(1, 4, 3)


In [55]:
print('last hidden state : {}, shape:{}'.format(last_state, last_state.shape))

last hidden state : [[-0.19777088 -0.04731996  0.29687196]], shape:(1, 3)


In [43]:
lstm = LSTM(3, return_sequences=False, return_state=True)
hidden_state, last_state, last_cell_state = lstm(train_x)
print('hidden state : {}, shape:{}'.format(hidden_state, hidden_state.shape))
print('last hidden state : {}, shape:{}'.format(last_state, last_state.shape))
print('last cell state : {}, shape:{}'.format(last_cell_state, last_cell_state.shape))

hidden state : [[-0.19777088 -0.04731996  0.29687196]], shape:(1, 3)
last hidden state : [[-0.19777088 -0.04731996  0.29687196]], shape:(1, 3)
last cell state : [[-0.4778415 -0.7473347  1.1227415]], shape:(1, 3)


In [44]:
lstm = LSTM(3, return_sequences=True, return_state=True)
hidden_states, last_hidden_state, last_cell_state=lstm(train_x)
print('hidden states : {}, shape:{}'.format(hidden_states, hidden_states.shape))
print('last hidden states : {}, shape:{}'.format(last_hidden_state, last_hidden_state.shape))
print('last cell state : {}, shape:{}'.format(last_cell_state, last_cell_state.shape))

hidden states : [[[-0.33422008  0.03967107  0.04859337]
  [-0.3556836   0.14815271  0.10450999]
  [-0.33277744  0.39397198  0.10796875]
  [-0.49650574  0.2670325   0.4388172 ]]], shape:(1, 4, 3)
last hidden states : [[-0.49650574  0.2670325   0.4388172 ]], shape:(1, 3)
last cell state : [[-0.91209656  0.782628    1.0019712 ]], shape:(1, 3)


In [54]:
#Bidirectional LSTM Keras

k_init = tf.keras.initializers.Constant(value=0.1)
b_init = tf.keras.initializers.Constant(value=0)
r_init = tf.keras.initializers.Constant(value=0.1)

bilstm = Bidirectional(LSTM(3, return_sequences=False, return_state=True,
kernel_initializer=k_init,bias_initializer=b_init, recurrent_initializer=r_init))
hidden_state, forword_h, forward_c, backward_h, backward_c= bilstm(train_x)

print('hidden states : {}, shape:{}'.format(hidden_state, hidden_states.shape))
print('forword states : {}, shape:{}'.format(forword_h, forward_h.shape))
print('backward states : {}, shape:{}'.format(backward_c, backward_c.shape))

hidden states : [[0.63031393 0.63031393 0.63031393 0.7038734  0.7038734  0.7038734 ]], shape:(1, 4, 3)
forword states : [[0.63031393 0.63031393 0.63031393]], shape:(1, 3)
backward states : [[1.6402447 1.6402447 1.6402447]], shape:(1, 3)
